<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_artistes',
		'title' => 'Artistes',
		'fields' => array (
			array (
				'key' => 'field_54111308e59b4',
				'label' => 'images',
				'name' => 'images_artist',
				'type' => 'gallery',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_54186500ff7a3',
				'label' => 'Citation',
				'name' => 'quote',
				'type' => 'qtranslate_textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_541889111da9f',
				'label' => 'Citation en',
				'name' => 'quote_en',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5418894c1daa0',
				'label' => 'Citation zn',
				'name' => 'quote_zn',
				'type' => 'textarea',
				'instructions' => 'Sans les Guillemets',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_54111102aa274',
				'label' => 'Artist Contact Email',
				'name' => 'artist_contact_email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5411111daa275',
				'label' => 'Artist Website',
				'name' => 'artist_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'artist',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'author',
				5 => 'format',
				6 => 'categories',
				7 => 'tags',
				8 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_exhibitions',
		'title' => 'Exhibitions',
		'fields' => array (
			array (
				'key' => 'field_54111163c1626',
				'label' => 'Titre court',
				'name' => 'titre_court',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_541861af37854',
				'label' => 'Artiste',
				'name' => 'artist-linked',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'artist',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_54111185c1628',
				'label' => 'Date Exhibition US',
				'name' => 'date_exhibition_us',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5411119dc1629',
				'label' => 'Date Exhibition FR',
				'name' => 'date_exhibition_fr',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_541111b1c162a',
				'label' => 'Date Exhibition ANNEE',
				'name' => 'date_exhibition_annee',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_541111e8c162b',
				'label' => 'Exhibition Place',
				'name' => 'exhibition_place',
				'type' => 'checkbox',
				'choices' => array (
					'paris' => 'Paris',
					'london' => 'London',
				),
				'default_value' => 'paris',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_54111280f7731',
				'label' => 'Images',
				'name' => 'images_show',
				'type' => 'gallery',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_54111258c162c',
				'label' => 'PDF',
				'name' => 'exhib_pdf',
				'type' => 'file',
				'save_format' => 'object',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'exhibition',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'author',
				5 => 'format',
				6 => 'categories',
				7 => 'tags',
				8 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_options',
		'title' => 'Options',
		'fields' => array (
			array (
				'key' => 'field_54171e99553ad',
				'label' => 'Logo',
				'name' => 'logoVnh',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_54171ea4553ae',
				'label' => 'Name',
				'name' => 'vnhName',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-global',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
